### ISSUE TITLE
How to install and what it does? 

### ISSUE THREAD

**Issue by shashj199** [timkpaine/knowledgelab#16]
@timkpaine Hey Tim,

I want to use this extension as part of my workflow. Can you let me know how to install it? So far I am unable to do so.

Thanks

**Comment by timkpaine** [comment]
this package is to interface with knowledgerepo from jupyterlab

**Comment by shashj199** [comment]
But how do we install and use it? Is there a documentation?

**Comment by timkpaine** [comment]
check the Makefile
